Repository CS2103JAN2018-W09-B1/main, pull requests merged in 2018-03, with the labels that each got.

#6 DeveloperGuide.adoc: add user stories
  docs/DeveloperGuide.adoc
Labels: type.story

#10 Add set command functionality
  docs/UserGuide.adoc
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/Command.java
  src/main/java/seedu/address/logic/commands/CommandWords.java
  src/main/java/seedu/address/logic/commands/SetCommand.java
  src/main/java/seedu/address/logic/commands/UndoableCommand.java
  src/main/java/seedu/address/logic/commands/exceptions/CommandWordException.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/SetCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/UserPrefs.java
  src/main/java/seedu/address/ui/CommandBox.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/systemtests/AddCommandSystemTest.java
  src/test/java/systemtests/AddressBookSystemTest.java
  src/test/java/systemtests/ClearCommandSystemTest.java
  src/test/java/systemtests/DeleteCommandSystemTest.java
  src/test/java/systemtests/EditCommandSystemTest.java
  src/test/java/systemtests/FindCommandSystemTest.java
  src/test/java/systemtests/SelectCommandSystemTest.java
Labels: priority.medium, status.ongoing, type.task

#13 Add new classes in Model component
  src/main/java/seedu/address/model/job/Job.java
  src/main/java/seedu/address/model/job/JobList.java
  src/main/java/seedu/address/model/job/JobNumber.java
  src/main/java/seedu/address/model/job/VehicleNumber.java
  src/main/java/seedu/address/model/job/exceptions/JobNotFoundException.java
  src/main/java/seedu/address/model/person/Email.java
  src/main/java/seedu/address/model/person/Name.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/Phone.java
  src/main/java/seedu/address/model/tag/Tag.java
Labels: priority.high, status.ongoing, type.task

#12 Add sort command
  src/main/java/seedu/address/logic/commands/SortCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/UniquePersonList.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/SortCommandTest.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: priority.medium, type.task

#34 Add theme command test cases
  src/main/java/seedu/address/logic/commands/ThemeCommand.java
  src/test/data/JsonUserPrefsStorageTest/TypicalUserPref.json
  src/test/java/seedu/address/logic/commands/ThemeCommandTest.java
  src/test/java/seedu/address/logic/parser/ThemeCommandParserTest.java
  src/test/java/seedu/address/testutil/TypicalIndexes.java
Labels: priority.medium

#39 V1.1 Documentation update
  README.adoc
  docs/DeveloperGuide.adoc
  docs/LearningOutcomes.adoc
  docs/UserGuide.adoc
  docs/images/CarviciM_logo.PNG
  docs/images/Ui.png
Labels: type.task

#41 Update AboutUs.adoc and User guide
  docs/AboutUs.adoc
  docs/UserGuide.adoc
  docs/images/charmaineleehc.jpg
Labels: priority.high

#54 Update RemarkList and Remark class
  src/main/java/seedu/address/model/remark/Remark.java
  src/main/java/seedu/address/model/remark/RemarkList.java
Labels: priority.high, status.ongoing

#63 DeveloperGuide.adoc: add implementation details for theme command
  docs/DeveloperGuide.adoc
Labels: type.task

#53 add job list UI support
  docs/DeveloperGuide.adoc
Labels: status.ongoing

#78 Add importAll command
  build.gradle
  src/main/java/seedu/address/logic/commands/CommandWords.java
  src/main/java/seedu/address/logic/commands/ImportAllCommand.java
  src/main/java/seedu/address/logic/commands/SetCommand.java
  src/main/java/seedu/address/logic/commands/exceptions/CommandWordException.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ImportAllCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/SetCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/job/Job.java
  src/main/java/seedu/address/model/session/ExcelColumnSpannable.java
  src/main/java/seedu/address/model/session/ExcelRowReference.java
  src/main/java/seedu/address/model/session/ImportSession.java
  src/main/java/seedu/address/model/session/JobEntry.java
  src/main/java/seedu/address/model/session/RowData.java
  src/main/java/seedu/address/model/session/SessionData.java
  src/main/java/seedu/address/model/session/SheetParser.java
  src/main/java/seedu/address/model/session/SheetWithHeaderFields.java
  src/main/java/seedu/address/model/session/exceptions/DataIndexOutOfBoundsException.java
  src/main/java/seedu/address/model/session/exceptions/FileAccessException.java
  src/main/java/seedu/address/model/session/exceptions/FileFormatException.java
  src/main/java/seedu/address/model/session/exceptions/InvalidDataException.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/AddJobCommandTest.java
  src/test/resources/model.session.ImportSessionTest/CS2103-testsheet.xlsx
  src/test/resources/model.session.ImportSessionTest/CS2103-testsheet.xlsx2018.03.25.23.24.19CS2103-testsheet.xlsx
Labels: priority.high, type.epic

#84 Add archive command
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/commons/util/FileUtil.java
  src/main/java/seedu/address/logic/commands/ArchiveCommand.java
  src/main/java/seedu/address/logic/commands/CommandWords.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ArchiveCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyAddressBook.java
  src/main/java/seedu/address/model/UserPrefs.java
  src/main/java/seedu/address/model/job/Date.java
  src/main/java/seedu/address/model/job/DateRange.java
  src/main/java/seedu/address/storage/ArchiveJobStorage.java
  src/main/java/seedu/address/storage/Storage.java
  src/main/java/seedu/address/storage/StorageManager.java
  src/main/java/seedu/address/storage/XmlArchiveJobStorage.java
  src/main/java/seedu/address/storage/XmlFileStorage.java
  src/main/java/seedu/address/storage/XmlSerializableArchiveJob.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/AddJobCommandTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/storage/StorageManagerTest.java
Labels: priority.medium, status.ongoing, type.epic, type.story

#83 Connect to gmail and authorize
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
  src/main/java/seedu/address/commons/GmailAuthenticator.java
  src/main/java/seedu/address/logic/commands/LoginCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/resources/client_secret.json
  src/test/java/seedu/address/storage/ImportSessionTest.java
Labels: priority.high, status.ongoing, type.enhancement, type.story
