Repository CS2103JAN2018-W09-B1/main, pull requests merged in 2018-04, with the labels that each got.

#92 Add documentation for import
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/images/SessionCloseSequenceDiagram.png
  docs/images/SessionComponentClassDiagram.png
  docs/images/SetCommandObjectDiagram.png
  docs/images/sessionInitializationSequenceDiagram.png
  docs/images/sessionReviewSequenceDiagram.png
  src/main/java/seedu/carvicim/storage/session/ImportSession.java
Labels: status.ongoing

#101 Send blank email
  build.gradle
  docs/UserGuide.adoc
  src/main/java/seedu/carvicim/commons/GmailAuthenticator.java
  src/main/java/seedu/carvicim/logic/commands/EmailCommand.java
  src/main/java/seedu/carvicim/logic/commands/LoginCommand.java
  src/main/java/seedu/carvicim/logic/parser/CarvicimParser.java
  src/test/java/seedu/carvicim/logic/commands/EmailCommandTest.java
Labels: priority.high, status.ongoing

#110 Add analyse command
  src/main/java/seedu/carvicim/logic/commands/AnalyseCommand.java
  src/main/java/seedu/carvicim/logic/commands/CommandWords.java
  src/main/java/seedu/carvicim/logic/parser/CarvicimParser.java
  src/main/java/seedu/carvicim/model/Carvicim.java
  src/main/java/seedu/carvicim/model/Model.java
  src/main/java/seedu/carvicim/model/ModelManager.java
  src/main/java/seedu/carvicim/model/job/JobList.java
  src/test/java/seedu/carvicim/logic/commands/AddEmployeeCommandTest.java
  src/test/java/seedu/carvicim/logic/commands/AddJobCommandTest.java
Labels: priority.medium, status.ongoing, type.enhancement, type.story

#117 V1.4.2
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  src/main/java/seedu/carvicim/commons/GmailAuthenticator.java
  src/main/java/seedu/carvicim/logic/commands/EmailCommand.java
  src/main/java/seedu/carvicim/logic/parser/CarvicimParser.java
  src/main/resources/.credentials/carvicim-gmail/StoredCredential
  src/test/java/seedu/carvicim/logic/commands/EmailCommandTest.java
  unused/LoginCommand.java
Labels: severity.Low, status.ongoing, type.task

#151 Import commands are fully undoable and persistent.
  .gitignore
  CS2103-testsheet.xlsx
  src/main/java/seedu/carvicim/logic/commands/AcceptAllCommand.java
  src/main/java/seedu/carvicim/logic/commands/AcceptCommand.java
  src/main/java/seedu/carvicim/logic/commands/ClearCommand.java
  src/main/java/seedu/carvicim/logic/commands/CommandWords.java
  src/main/java/seedu/carvicim/logic/commands/ImportAllCommand.java
  src/main/java/seedu/carvicim/logic/commands/ImportCommand.java
  src/main/java/seedu/carvicim/logic/commands/RejectAllCommand.java
  src/main/java/seedu/carvicim/logic/commands/RejectCommand.java
  src/main/java/seedu/carvicim/logic/commands/SaveCommand.java
  src/main/java/seedu/carvicim/logic/commands/SwitchCommand.java
  src/main/java/seedu/carvicim/logic/commands/UndoableCommand.java
  src/main/java/seedu/carvicim/logic/parser/CarvicimParser.java
  src/main/java/seedu/carvicim/model/UserPrefs.java
  src/main/java/seedu/carvicim/storage/session/ImportSession.java
  src/main/java/seedu/carvicim/storage/session/JobEntry.java
  src/main/java/seedu/carvicim/storage/session/SessionData.java
  src/main/java/seedu/carvicim/storage/session/SheetParser.java
  src/main/java/seedu/carvicim/storage/session/SheetWithHeaderFields.java
  src/main/java/seedu/carvicim/storage/session/exceptions/UninitializedException.java
  src/test/java/seedu/carvicim/logic/commands/AddEmployeeCommandTest.java
  src/test/java/seedu/carvicim/storage/ImportSessionTest.java
Labels: priority.high, type.epic

#162 Portfolio and DeveloperGuide update
  docs/AboutUs.adoc
  docs/DeveloperGuide.adoc
  docs/images/AddJobCommand_execute_SeqDiag.png
  docs/images/AddJobCommand_preprocess_SeqDiag.png
  docs/images/CloseJobCommand_execute_SeqDiag.png
  docs/images/CloseJobCommand_preprocess_SeqDiag.png
  docs/team/owzhenwei.adoc
Labels: status.ongoing, type.task

#176 V1.5
  collated/functional/charmaineleehc-reused.md
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/images/EmailCommand_SeqDiagram.PNG
  docs/images/LoginCommand_SeqDiagram.PNG
  docs/team/charmaineleehc.adoc
  src/main/java/seedu/carvicim/commons/GmailAuthenticator.java
  src/main/java/seedu/carvicim/logic/commands/EmailCommand.java
  src/main/java/seedu/carvicim/logic/commands/LoginCommand.java
  src/main/java/seedu/carvicim/logic/parser/CarvicimParser.java
  src/main/java/seedu/carvicim/logic/parser/EmailCommandParser.java
  src/test/java/seedu/carvicim/logic/commands/EmailCommandTest.java
  src/test/java/seedu/carvicim/logic/parser/CarvicimParserTest.java
  src/test/java/seedu/carvicim/logic/parser/EmailCommandParserTest.java
  src/test/java/seedu/carvicim/logic/parser/FindByTagCommandParserTest.java
  src/test/java/seedu/carvicim/model/person/TagContainsKeywordsPredicateTest.java
Labels: priority.high, status.ongoing

#185 V1.5 documentation2
  README.adoc
  build.gradle
  collated/functional/yuhongherald.md
  collated/test/yuhongherald.md
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/team/yuhongherald.adoc
  src/main/java/seedu/carvicim/logic/commands/AcceptAllCommand.java
  src/main/java/seedu/carvicim/logic/commands/CommandWords.java
  src/main/java/seedu/carvicim/logic/commands/ImportAllCommand.java
  src/main/java/seedu/carvicim/logic/commands/RejectAllCommand.java
  src/main/java/seedu/carvicim/logic/commands/SetCommand.java
  src/main/java/seedu/carvicim/logic/commands/exceptions/CommandException.java
  src/main/java/seedu/carvicim/model/job/JobList.java
  src/main/java/seedu/carvicim/storage/session/ImportSession.java
  src/main/java/seedu/carvicim/storage/session/JobEntry.java
  src/main/java/seedu/carvicim/storage/session/RowData.java
  src/main/java/seedu/carvicim/storage/session/SessionData.java
  src/main/java/seedu/carvicim/storage/session/SheetParser.java
  src/main/java/seedu/carvicim/storage/session/SheetWithHeaderFields.java
  src/test/java/seedu/carvicim/logic/commands/AcceptAllCommandTest.java
  src/test/java/seedu/carvicim/logic/commands/AcceptCommandTest.java
  src/test/java/seedu/carvicim/logic/commands/ImportAllCommandTest.java
  src/test/java/seedu/carvicim/logic/commands/ImportCommandTest.java
  src/test/java/seedu/carvicim/logic/commands/RejectAllCommandTest.java
  src/test/java/seedu/carvicim/logic/commands/RejectCommandTest.java
  src/test/java/seedu/carvicim/logic/commands/SetCommandTest.java
  src/test/java/seedu/carvicim/storage/ImportSessionTestEnv.java
Labels: status.ongoing
